### ISSUE TITLE
Not Downloading

### ISSUE THREAD

**Issue by moh1122** [nevercry/VideoSaver#1]
Hello
I really like your proj
but its not downloading it shows tht its working fine but after the download is done i go to the app its empty, any clue?

**Comment by nevercry** [comment]
Hi, thanks for feedback. Could you give me more information about the issues, like Screenshot or something? My App could only download the mp4 file. Your need create your own App Group ID for both app and extension. You could pull down to refresh the  cache folder to load new downloaded videos.

**Comment by moh1122** [comment]
thnk u
