### ISSUE TITLE
VideoMarks找不到IPA。

### ISSUE THREAD

**Issue by yuanfang250** [nevercry/VideoSaver#2]
最近搜索到这个项目，真的不错，还在维护吗？
APPSTORE里没有任何痕迹，现在有什么方案可以实现类似的IOS视频本地下载。

**Comment by nevercry** [comment]
代码我开源的，你可以自己编译个？替代品也可以用苹果自己的快捷指令来实现。苹果商店是上架不了，因为不允许有侵犯视频网站版权的行为，比如在未获得许可的情况下，下载网站的视频。

**Comment by yuanfang250** [comment]
﻿
﻿谢谢告知，ios门外汉。
我先学习一下编译。
